const express = require("express");
const hostRouter = express.Router();
const hostController = require("../controllers/hostController");
hostRouter.get("/host/add-home",hostController.getAddHome); 
hostRouter.get("/host/host-home-list",hostController.getHostHomes); 
hostRouter.get("/host/edit-home/:homeId",hostController.getEditHome);
hostRouter.post("/host/add-home",hostController.postAddHome);
hostRouter.post("/host/edit-home", hostController.postEditHome);
hostRouter.post("/host/delete-home/:homeId", hostController.postDeleteHome);
module.exports = hostRouter;