const express = require('express');
const storeRouter = express.Router();
const storeController = require('../controllers/storeController');
storeRouter.get('/homes', storeController.getHome);
storeRouter.get('/bookings', storeController.getBookings);
storeRouter.get('/favourites', storeController.getFavourites);
storeRouter.get('/', storeController.getIndex);
storeRouter.post('/favourites', storeController.postAddToFavourites);
storeRouter.post('/favourites/delete/:homeId', storeController.postDeleteFavourite);
storeRouter.get('/homes/:homeId', storeController.getHomeDetails);
module.exports = storeRouter;